-- V21: 趋势波段交易系统（科技股回踩/突破 + 动态止盈止损）
-- 用户私有池；信号推送 Server酱 的同时系统自动记账（HYBRID）

CREATE TABLE IF NOT EXISTS swing_watchlist (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    stock_code VARCHAR(20) NOT NULL,
    stock_name VARCHAR(64),
    sector_tag VARCHAR(64) NOT NULL,
    thesis VARCHAR(500),
    hard_filter_ok TINYINT NOT NULL DEFAULT 1,
    quiet_period TINYINT NOT NULL DEFAULT 0,
    preferred_setup VARCHAR(20) NOT NULL DEFAULT 'BOTH',
    trade_mode VARCHAR(16) NOT NULL DEFAULT 'HYBRID',
    status VARCHAR(32) NOT NULL,
    account_equity DECIMAL(14,2) DEFAULT 100000.00,
    max_position_pct DECIMAL(5,2) DEFAULT 15.00,
    serverchan_send_key VARCHAR(128),
    note VARCHAR(500),
    last_scan_at DATETIME,
    last_signal_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_swing_user_stock (user_id, stock_code),
    KEY idx_swing_watch_status (status),
    KEY idx_swing_watch_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS swing_setup (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    watch_id BIGINT NOT NULL,
    setup_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    ma5 DECIMAL(12,4),
    ma10 DECIMAL(12,4),
    ma20 DECIMAL(12,4),
    ma60 DECIMAL(12,4),
    ma20_slope DECIMAL(12,6),
    vol_ma20 BIGINT,
    vol_ma60 BIGINT,
    vol_ratio DECIMAL(8,4),
    limit_up_date DATE,
    limit_up_open DECIMAL(10,2),
    limit_up_low DECIMAL(10,2),
    limit_up_close DECIMAL(10,2),
    limit_up_volume BIGINT,
    pullback_zone_high DECIMAL(10,2),
    pullback_zone_low DECIMAL(10,2),
    platform_high DECIMAL(10,2),
    platform_start DATE,
    platform_end DATE,
    platform_days INT,
    expire_date DATE,
    invalid_reason VARCHAR(255),
    detected_at DATETIME NOT NULL,
    triggered_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY idx_swing_setup_watch (watch_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS swing_position (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    watch_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    stock_code VARCHAR(20) NOT NULL,
    setup_id BIGINT,
    setup_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    entry_time DATETIME NOT NULL,
    avg_cost DECIMAL(10,2) NOT NULL,
    shares INT NOT NULL DEFAULT 0,
    initial_shares INT NOT NULL,
    peak_price DECIMAL(10,2) NOT NULL,
    realized_pnl DECIMAL(14,2) DEFAULT 0,
    unrealized_pnl DECIMAL(14,2),
    stop_price DECIMAL(10,2) NOT NULL,
    hard_stop_price DECIMAL(10,2) NOT NULL,
    soft_stop_pct DECIMAL(6,4),
    trail_drawdown_pct DECIMAL(6,4),
    locked_profit_pct DECIMAL(6,4),
    profit_tier VARCHAR(16) NOT NULL DEFAULT 'T0',
    add_count INT NOT NULL DEFAULT 0,
    partial_exits INT NOT NULL DEFAULT 0,
    ma20_break_days INT NOT NULL DEFAULT 0,
    exit_time DATETIME,
    exit_reason VARCHAR(64),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_swing_pos_watch (watch_id),
    KEY idx_swing_pos_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS swing_fill (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    position_id BIGINT NOT NULL,
    watch_id BIGINT NOT NULL,
    side VARCHAR(8) NOT NULL,
    reason VARCHAR(32) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    shares INT NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    fill_time DATETIME NOT NULL,
    source VARCHAR(16) NOT NULL,
    signal_id BIGINT,
    note VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY idx_swing_fill_pos (position_id),
    KEY idx_swing_fill_watch_time (watch_id, fill_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS swing_signal (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    watch_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    setup_id BIGINT,
    position_id BIGINT,
    signal_type VARCHAR(40) NOT NULL,
    level VARCHAR(16) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    trigger_price DECIMAL(10,2),
    suggest_action VARCHAR(32),
    suggest_shares INT,
    suggest_stop DECIMAL(10,2),
    status VARCHAR(20) NOT NULL,
    dedupe_key VARCHAR(128) NOT NULL,
    notified_at DATETIME,
    acked_at DATETIME,
    executed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_swing_signal_dedupe (dedupe_key),
    KEY idx_swing_signal_pending (user_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS swing_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    watch_id BIGINT NOT NULL,
    position_id BIGINT,
    event_type VARCHAR(40) NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32),
    payload_json JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY idx_swing_event_watch_time (watch_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
